kafka {
  bootstrap.servers = "localhost:9092"
  topic.meters = "smart-meters"
  topic.weather = "weather-data"
  producer.interval.ms = 1000
}

spark {
  app.name = "SmartMetersStreamingApp"
  master = "local[*]"
  checkpoint.dir = "/tmp/spark-checkpoints"
}

paths {
  data.dir = "data"
  meters.halfhourly = "data/halfhourly_dataset"
  meters.daily = "data/daily_dataset"
  households.info = "data/informations_households.csv"
  acorn.details = "data/acorn_details.csv"
  weather.hourly = "data/weather_hourly_darksky.csv"
  weather.daily = "data/weather_daily_darksky.csv"
  checkpoint = "data/checkpoint"
} 